name: Copy filters.js
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy filters.js
        run: |
          cp https://raw.githubusercontent.com/authifyWeb/filters/main/URL/filters.js \
            https://raw.githubusercontent.com/webVerts/wSource/main/fame/filters.js
