name: Copy and Minify JS File

on:
  schedule:
    - cron: "0 * * * *"  # Triggers at the 0th minute of every hour (UTC)
  workflow_dispatch:  

jobs:
  copy-and-minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: authifyWeb/filters  # Source repository
          path: URL/
      - uses: actions/checkout@v3
        with:
          repository: webVerts/wSource  # Target repository
          path: fame/
      - name: Copy file
        run: cp source-repo/URL/filters.js target-repo/path/to/filters.js
      - name: Commit changes
        run: |
          git add target-repo/path/to/filters.js
          git commit -m "Copy filters.js"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
