name: Test Workflow
on: 
  
  workflow_dispatch:
jobs:
  build:
    name: Copy JSON specs to ailabs-cli config Repo
    runs-on: ubuntu-latest
    steps:
      - name: Push JSON schema for YAML configuration of CLI
        uses: RomanosTrechlis/actions-copy-files@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          source-files: 'https://github.com/authifyWeb/filters/blob/main/URL/filters.js'
          destination-username: 'webVerts'
          destination-repository: 'wSource'
          destination-directory: 'fame/'
          commit-email: '100699190+webVerts@users.noreply.github.com'
          commit-username: 'webVerts'
