name: MergeFolder
on:
  workflow_dispatch: 
  jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initiate Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Update Filter
        run: python filter_updates.py
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: Automatically updated using GitHub Actions
