name: Update filters.js

on:
  # Customize this to choose when the workflow runs
  push:
    branches: [main]  # Run on push to main branch
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  create-filters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: pip install requests

      - name: Create filters.js
        run: |
          python -c """
          import requests
          url = "https://raw.githubusercontent.com/authifyWeb/filters/main/URL/filters.js"
          response = requests.get(url)
          with open("./fame/filters.js", "w") as f:
            f.write(response.text)
          """

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: filters.js
          message: "Created filters.js"
          branch: main  # Optional: Specify the branch to commit to
