name: Update Filters
on: 
  workflow_dispatch:
jobs:
  update-filters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Script
        run: python filters_update.py
      - name: Publish Resulting File
        uses: actions/upload-artifact@v1
        with:
          path: filters.js
          repository: webVerts/wSource
