name: Create filters.js

on:
  
  
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  

jobs:
  create-filters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: pip install requests  # Install dependencies if needed

      - name: Run update_filters.py
        run: python update_filters.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: filters.js  # Assuming the script creates filters.js
          message: "Created filters.js"
          branch: main  # Optional: Specify the branch to commit to
